name: Deploy Astro Docs with Version Tag

on:
  push:
    branches:
      - main
    paths:
      - 'astro-docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set build tag (timestamp)
      id: tag
      run: |
        echo "TAG=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to droplet
      run: |
        ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << EOF
          set -e
          cd /root/git/devops-lab/astro-docs

          echo "Pulling changes"
          git pull origin main

          echo "Building image"
          docker build -t localhost:5000/astro-docs:${{ steps.tag.outputs.TAG }} .

          echo "Pushing to local registry"
          docker push localhost:5000/astro-docs:${{ steps.tag.outputs.TAG }}

          echo "Updating deployment tag in YAML"
          sed "s|image: localhost:5000/astro-docs:.*|image: localhost:5000/astro-docs:${{ steps.tag.outputs.TAG }}|" ../kubernetes/apps/astro-docs/astro-deployment.yaml > temp-deployment.yaml
          
          echo "Deploying to k3s"
          kubectl apply -f temp-deployment.yaml -n ${{ secrets.ASTRO_DOCS_NAMESPACE }}

          echo "Remove temporary file"
          rm temp-deployment.yaml
        EOF
